### ISSUE TITLE
how to obtain?

### ISSUE THREAD

**Issue by subzero911** [maximrouf/VuforiaStandaloneBuild#2]
There is build demo only here. Where can I download a Vuforia Standalone package?
(Тут только демка с роботом, а где скачать сам ассет для компиляции в exe?)

**Comment by maximrouf** [comment]
Откройте демо-билд. В режиме трекинга есть кнопка (WWW) нажмите на нее и попадете на web-станицу с деталями.

**Comment by nischelwitzer** [comment]
hello, is it possible to test/try/buy it?
thanks alex

PS i have send you also an email to your augmented.cv email adress last week.

**Comment by MILL-Syp** [comment]
I also want to ask where to download, I'm sorry, I can't understand Russian.

**Comment by maximrouf** [comment]
For all question, please mail to me - augmented.cv@gmail.com
