### ISSUE TITLE
Question: Did you do something special ?

### ISSUE THREAD

**Issue by EloiStree** [maximrouf/VuforiaStandaloneBuild#4]
Hello, Like apparently hundred of other people on the web I don't succed to run the app as exe. (Blacks screen bug).

You are my hope as you have zip in this project an exe that is working.
And you are the one on most of those forum.

Is there something special to do ?
Or is it juste me that is no configuring my Unity correctly ?

(I am on unity 2020.3 with Vuforia 10.6)

**Comment by EloiStree** [comment]
(If it can help somone that fall here)
Note: I saw that Vuforia.dll in the package is editor only. And so the build fail. I will look around this direction.

**Comment by maximrouf** [comment]
To everyone who got here - "Vuforia Standalone" is an in-depth modification of the original plugin.
